export const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    FAILED_DEPENDENCY: 424,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
    INVALID_SESSION_REQUEST: "INVALID_SESSION_REQUEST",
    UNAUTHORIZED_INTERNAL_REQUEST: "UNAUTHORIZED_INTERNAL_REQUEST",
    ACTIVE_SESSION_CONFLICT: "ACTIVE_SESSION_CONFLICT",
    USER_VALIDATION_FAILED: "USER_VALIDATION_FAILED",
    USER_SERVICE_UNAVAILABLE: "USER_SERVICE_UNAVAILABLE",
    QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
    QUESTION_SERVICE_UNAVAILABLE: "QUESTION_SERVICE_UNAVAILABLE",
    SESSION_CREATION_FAILED: "SESSION_CREATION_FAILED",
} as const;

export const DEFAULTS = {
    SERVER_PORT: 3003,
    SESSION_TTL_MS: 60 * 60 * 1000,
    DEPENDENCY_TIMEOUT_MS: 5000,
    REDIS_PORT: 6379,
    REDIS_DB: 0,
    STUB_QUESTION_PREFIX: "stub",
} as const;
