ALTER TABLE attempts ADD COLUMN IF NOT EXISTS question_title TEXT NOT NULL DEFAULT '';
ALTER TABLE attempts ADD COLUMN IF NOT EXISTS total_test_cases INTEGER NOT NULL DEFAULT 0;
ALTER TABLE attempts ADD COLUMN IF NOT EXISTS test_cases_passed INTEGER NOT NULL DEFAULT 0;
